#!/usr/bin/env python3
"""
Generates src/mapData.js  (static level layout for "Nacht der Untoten"-inspired bunker).

Legend used in the emitted ASCII:
  ' ' exterior ground (walkable, zombies spawn here)
  '.' interior floor
  '#' wall
  'W' window / barricade (breakable, zombies climb in here)
  'D' buyable door (indestructible for zombies, player buys it)
  'c' crate  (solid prop)
  'r' rubble (walkable decor)
  '@' player start
  '1'..'4' wall-buy weapon spots (plaque sits on the wall behind)
  'g' grenade crate
"""
import os

W, H = 48, 32

g = [[' '] * W for _ in range(H)]

# ---------------------------------------------------------------- building ---
# exterior walls
for x in range(3, 45):
    g[4][x] = '#'
    g[27][x] = '#'
for y in range(4, 28):
    g[y][3] = '#'
    g[y][44] = '#'

# interior partition walls
for y in range(5, 27):
    g[y][23] = '#'
for x in range(4, 44):
    g[15][x] = '#'

# floors  A(nw) B(ne) C(sw) D(se)
for y in range(5, 15):
    for x in range(4, 23):
        g[y][x] = '.'
for y in range(5, 15):
    for x in range(24, 44):
        g[y][x] = '.'
for y in range(16, 27):
    for x in range(4, 23):
        g[y][x] = '.'
for y in range(16, 27):
    for x in range(24, 44):
        g[y][x] = '.'

# ------------------------------------------------------------------ doors ----
DOORS = [
    (23, 9, 750, 'B'),    # A <-> B
    (23, 21, 1000, 'D'),  # C <-> D
    (13, 15, 500, 'C'),   # A <-> C  (stairwell)
    (34, 15, 750, 'D'),   # B <-> D  (stairwell)
]
for x, y, cost, _ in DOORS:
    g[y][x] = 'D'

# ---------------------------------------------------------------- windows ----
WINDOWS = []
for x0 in (8, 17, 29, 38):
    WINDOWS += [(x0, 4), (x0 + 1, 4)]
    WINDOWS += [(x0, 27), (x0 + 1, 27)]
for y0 in (7, 12, 19, 24):
    WINDOWS += [(3, y0), (3, y0 + 1)]
    WINDOWS += [(44, y0), (44, y0 + 1)]
for x, y in WINDOWS:
    g[y][x] = 'W'

# ------------------------------------------------------------------ props ----
CRATES = [(19, 6), (20, 6), (6, 12), (27, 6), (40, 12),
          (19, 25), (6, 20), (27, 25), (40, 20), (12, 8), (35, 22)]
for x, y in CRATES:
    g[y][x] = 'c'

RUBBLE = [(10, 22), (11, 22), (31, 10), (32, 10), (18, 18), (29, 19),
          (7, 25), (41, 6), (26, 24), (16, 12)]
for x, y in RUBBLE:
    g[y][x] = 'r'

# ------------------------------------------------------------- wall buys -----
# (tile the player stands on, wall tile behind it, weapon id)
WALL_BUYS = [
    (6, 5, 6, 4, 'm1911'),
    (13, 5, 13, 4, 'thompson'),
    (34, 5, 34, 4, 'trenchgun'),
    (13, 26, 13, 27, 'mp40'),
    (34, 26, 34, 27, 'kar98k'),
]
for x, y, _, _, _ in WALL_BUYS:
    g[y][x] = '1'

GRENADES = [(20, 13), (28, 17)]
for x, y in GRENADES:
    g[y][x] = 'g'

PLAYER_START = (13, 10)
g[PLAYER_START[1]][PLAYER_START[0]] = '@'

# ----------------------------------------------------------- spawn points ----
SPAWNS = [
    (8, 1), (17, 0), (23, 1), (29, 0), (38, 1),
    (8, 30), (17, 31), (23, 30), (29, 31), (38, 30),
    (1, 7), (0, 12), (1, 19), (0, 24),
    (46, 7), (47, 12), (46, 19), (47, 24),
]

# ------------------------------------------------------------- validation ----
for row in g:
    assert len(row) == W, "row length"
assert len(g) == H

# sanity: every walkable interior tile reachable from player start through
# floors + doors + windows
import collections
start = PLAYER_START
walk = lambda ch: ch in '.WDc r@1g'
seen = {start}
q = collections.deque([start])
while q:
    x, y = q.popleft()
    for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
        nx, ny = x + dx, y + dy
        if 0 <= nx < W and 0 <= ny < H and (nx, ny) not in seen and walk(g[ny][nx]):
            seen.add((nx, ny))
            q.append((nx, ny))
for x, y in SPAWNS:
    assert g[y][x] == ' ', (x, y, g[y][x])
    assert (x, y) in seen, "spawn not connected: %s" % ((x, y),)
for x, y, _, _, _ in WALL_BUYS:
    assert (x, y) in seen, "wall buy not connected"

rooms = {'A': [], 'B': [], 'C': [], 'D': []}
for y in range(H):
    for x in range(W):
        if g[y][x] == '.':
            if x < 23 and y < 15:
                rooms['A'].append((x, y))
            elif x > 23 and y < 15:
                rooms['B'].append((x, y))
            elif x < 23 and y > 15:
                rooms['C'].append((x, y))
            elif x > 23 and y > 15:
                rooms['D'].append((x, y))
for k, v in rooms.items():
    print("room %s: %d floor tiles" % (k, len(v)))
print("interior tiles reachable:", len(seen))

# ---------------------------------------------------------------- emit js ----
here = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(here, '..', 'src', 'mapData.js')
rows_js = ",\n  ".join('"%s"' % "".join(r) for r in g)

js = '''// AUTO-GENERATED by tools/genmap.py -- do not edit by hand.
// Legend: ' ' exterior ground | '.' floor | '#' wall | 'W' window/barricade
//         'D' buyable door | 'c' crate (solid) | 'r' rubble (walkable decor)
//         '@' player start | '1' wall-buy spot | 'g' grenade crate

export const MAP_W = %d;
export const MAP_H = %d;

export const MAP_ROWS = [
  %s
];

export const PLAYER_START = { x: %d, y: %d };

export const SPAWN_POINTS = [
%s
];

// [standX, standY, wallX, wallY, weaponId, price]
export const WALL_BUYS = [
%s
];

export const GRENADE_CRATES = [
%s
];
''' % (
    W, H, rows_js,
    PLAYER_START[0], PLAYER_START[1],
    ",\n".join("  { x: %d, y: %d }" % s for s in SPAWNS),
    ",\n".join("  { x: %d, y: %d, wx: %d, wy: %d, weapon: '%s' }" % wb for wb in WALL_BUYS),
    ",\n".join("  { x: %d, y: %d }" % s for s in GRENADES),
)

with open(out, 'w') as f:
    f.write(js)
print("wrote", os.path.abspath(out))
