// Weapon definitions + ammo state.

export const WEAPONS = {
  m1911: {
    id: 'm1911',
    name: 'M1911',
    art: 'm1911',
    auto: false,
    dmg: 60,
    headMul: 2.4,
    pellets: 1,
    magSize: 8,
    reserveMax: 120,
    startReserve: 96,
    fireDelay: 0.17,
    reloadTime: 1.45,
    spread: 0.010,
    spreadMove: 0.035,
    recoil: 1.6,
    pierce: 0,
    range: 900,
    price: 0,
    ammoPrice: 120,
    sound: 'pistol',
    tracer: '#ffd9a0',
    kick: 1.1,
    tier: 0,
  },
  thompson: {
    id: 'thompson',
    name: 'Thompson',
    art: 'thompson',
    auto: true,
    dmg: 55,
    headMul: 2.2,
    pellets: 1,
    magSize: 20,
    reserveMax: 240,
    startReserve: 180,
    fireDelay: 0.078,
    reloadTime: 2.35,
    spread: 0.028,
    spreadMove: 0.06,
    recoil: 1.5,
    pierce: 0,
    range: 800,
    price: 1200,
    ammoPrice: 600,
    sound: 'smg',
    tracer: '#ffcf8a',
    kick: 1.5,
    tier: 1,
  },
  mp40: {
    id: 'mp40',
    name: 'MP40',
    art: 'mp40',
    auto: true,
    dmg: 50,
    headMul: 2.2,
    pellets: 1,
    magSize: 32,
    reserveMax: 288,
    startReserve: 192,
    fireDelay: 0.088,
    reloadTime: 2.6,
    spread: 0.032,
    spreadMove: 0.065,
    recoil: 1.3,
    pierce: 0,
    range: 760,
    price: 1000,
    ammoPrice: 500,
    sound: 'smg',
    tracer: '#ffd7a2',
    kick: 1.2,
    tier: 1,
  },
  trenchgun: {
    id: 'trenchgun',
    name: 'M1897 Trench Gun',
    art: 'trenchgun',
    auto: false,
    dmg: 34,
    headMul: 1.5,
    pellets: 6,
    magSize: 6,
    reserveMax: 72,
    startReserve: 48,
    fireDelay: 0.72,
    reloadTime: 3.4,
    spread: 0.115,
    spreadMove: 0.14,
    recoil: 4.5,
    pierce: 0,
    range: 420,
    price: 1200,
    ammoPrice: 600,
    sound: 'shotgun',
    tracer: '#ffc27a',
    kick: 5.5,
    tier: 2,
  },
  kar98k: {
    id: 'kar98k',
    name: 'Kar98k',
    art: 'kar98k',
    auto: false,
    dmg: 330,
    headMul: 2.6,
    pellets: 1,
    magSize: 5,
    reserveMax: 90,
    startReserve: 60,
    fireDelay: 1.05,
    reloadTime: 3.1,
    spread: 0.004,
    spreadMove: 0.05,
    recoil: 5,
    pierce: 3,
    range: 1200,
    price: 1500,
    ammoPrice: 750,
    sound: 'rifle',
    tracer: '#fff0c0',
    kick: 6,
    tier: 3,
  },
};

export const WEAPON_ORDER = ['m1911', 'mp40', 'thompson', 'trenchgun', 'kar98k'];

export const GRENADE_PRICE = 250;
export const GRENADE_MAX = 4;

export function makeLoadout() {
  const out = {};
  for (const id of Object.keys(WEAPONS)) {
    const w = WEAPONS[id];
    out[id] = { id, mag: w.magSize, reserve: id === 'm1911' ? w.startReserve : 0, owned: id === 'm1911' };
  }
  return out;
}

export function totalAmmo(slot, def) {
  return slot.mag + slot.reserve;
}
